services:
  api:
    image: oseniasjunior/api-task
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    command: sh -c "python manage.py migrate && gunicorn DesafioAngularBackend.wsgi --bind 0.0.0.0:3000"

